[workspace]
resolver = "2"
members = ["crates/core", "crates/publish", "crates/client", "crates/cli", "app/src-tauri", "admin/src-tauri"]

[workspace.package]
edition = "2021"
version = "1.1.0"
license = "MIT OR Apache-2.0"
authors = ["Jonas"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10"
zip = { version = "2", default-features = false, features = ["deflate"] }
toml = "0.8"
thiserror = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
time = { version = "0.3", features = ["formatting"] }
sha2 = "0.10"
ed25519-dalek = "2"
getrandom = "0.3"
fastnbt = "2"
tempfile = "3"
proptest = "1"
